apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstpod
  template:
    metadata:
      labels:
        app: myfirstpod
    spec:
      containers:
        - name: mycontainer
          image: nginx
